"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { CalendarClock, Info } from "lucide-react";
import {
  CATEGORIES,
  DEFAULT_VAT_CATEGORY,
  DEFAULT_VAT_METHOD,
  VAT_CATEGORIES,
  VAT_METHODS,
  generateDeadlines,
  type Category,
  type Deadline,
  type VatCategory,
  type VatMethod,
} from "@/lib/rules/compliance-calendar";

const CATEGORY_STYLES: Record<Category, { badge: string; dot: string }> = {
  "PAYE":             { badge: "bg-purple-50 text-purple-700 border-purple-200", dot: "bg-purple-500" },
  "VAT":               { badge: "bg-orange-50 text-orange-700 border-orange-200", dot: "bg-orange-500" },
  "Provisional Tax":   { badge: "bg-amber-50 text-amber-700 border-amber-200", dot: "bg-amber-500" },
  "Income Tax":        { badge: "bg-red-50 text-red-700 border-red-200", dot: "bg-red-500" },
  "CIPC":              { badge: "bg-blue-50 text-blue-700 border-blue-200", dot: "bg-blue-500" },
  "COIDA":             { badge: "bg-teal-50 text-teal-700 border-teal-200", dot: "bg-teal-500" },
};

/*
 * Dates are generated by lib/rules/compliance-calendar.ts from structured rules,
 * with the SARS weekend / public-holiday adjustment applied per obligation.
 *
 * Static build safety: the server render (and a no-JS visit) shows the full
 * calendar for the window, because the server cannot know the visitor's "today".
 * After hydration the client reads the real date and hides passed deadlines.
 */

function todayIso(): string {
  const d = new Date();
  const p = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
}

function daysUntil(iso: string, today: string): number {
  const a = new Date(iso + "T00:00:00Z").getTime();
  const b = new Date(today + "T00:00:00Z").getTime();
  return Math.round((a - b) / 86400000);
}

function formatDate(iso: string): string {
  return new Date(iso + "T00:00:00Z").toLocaleDateString("en-ZA", {
    day: "numeric", month: "short", year: "numeric", timeZone: "UTC",
  });
}

function monthHeading(key: string): string {
  return new Date(key + "-01T00:00:00Z").toLocaleDateString("en-ZA", {
    month: "long", year: "numeric", timeZone: "UTC",
  });
}

export default function ComplianceCalendar() {
  const [activeFilter, setActiveFilter] = useState<Category | "All">("All");
  const [vatCategory, setVatCategory] = useState<VatCategory>(DEFAULT_VAT_CATEGORY);
  const [vatMethod, setVatMethod] = useState<VatMethod>(DEFAULT_VAT_METHOD);
  // null until mounted: server HTML and no-JS show everything.
  const [today, setToday] = useState<string | null>(null);

  useEffect(() => {
    setToday(todayIso());
  }, []);

  const all = useMemo(
    () => generateDeadlines({ vatCategory, vatMethod }),
    [vatCategory, vatMethod]
  );

  const { upcoming, grouped, hiddenPassed } = useMemo(() => {
    const filtered = activeFilter === "All" ? all : all.filter((d) => d.category === activeFilter);
    const visible = today ? filtered.filter((d) => d.date >= today) : filtered;
    const upcoming = today ? visible.slice(0, 3) : [];
    const byMonth = new Map<string, Deadline[]>();
    for (const d of visible) {
      const key = d.date.slice(0, 7);
      if (!byMonth.has(key)) byMonth.set(key, []);
      byMonth.get(key)!.push(d);
    }
    return { upcoming, grouped: byMonth, hiddenPassed: filtered.length - visible.length };
  }, [all, activeFilter, today]);

  return (
    <div className="bg-white rounded-2xl border border-neutral-200 overflow-hidden">
      {/* Header */}
      <div className="bg-brand px-6 py-5 flex items-center gap-3">
        <div className="w-10 h-10 rounded-xl bg-white/10 flex items-center justify-center">
          <CalendarClock size={20} className="text-white" />
        </div>
        <div>
          <h2 className="text-base font-bold text-white">SARS Compliance Calendar, 2026/27</h2>
          <p className="text-xs text-brand-100">Every recurring PAYE, VAT, provisional tax, and reconciliation deadline in one place</p>
        </div>
      </div>

      <div className="p-6 space-y-6">
        {/* Filter chips */}
        <div>
          <p className="text-xs font-semibold text-neutral-500 uppercase tracking-wider mb-2">Filter by category</p>
          <div className="flex flex-wrap gap-2">
            <button
              onClick={() => setActiveFilter("All")}
              aria-pressed={activeFilter === "All"}
              className={`text-xs font-medium px-3 py-1.5 rounded-full border transition-colors ${
                activeFilter === "All"
                  ? "bg-brand text-white border-brand"
                  : "bg-white text-neutral-600 border-neutral-200 hover:border-brand/40"
              }`}
            >
              All
            </button>
            {CATEGORIES.map((cat) => (
              <button
                key={cat}
                onClick={() => setActiveFilter(cat)}
                aria-pressed={activeFilter === cat}
                className={`text-xs font-medium px-3 py-1.5 rounded-full border transition-colors ${
                  activeFilter === cat
                    ? "bg-brand text-white border-brand"
                    : `${CATEGORY_STYLES[cat].badge} hover:border-brand/40`
                }`}
              >
                {cat}
              </button>
            ))}
          </div>
        </div>

        {/* VAT selection */}
        <div className="grid sm:grid-cols-2 gap-3">
          <div>
            <label htmlFor="vat-category" className="block text-xs font-semibold text-neutral-500 uppercase tracking-wider mb-1.5">
              VAT category
            </label>
            <select
              id="vat-category"
              value={vatCategory}
              onChange={(e) => setVatCategory(e.target.value as VatCategory)}
              className="w-full border border-neutral-200 rounded-lg text-sm px-3 py-2 bg-white"
            >
              {VAT_CATEGORIES.map((c) => (
                <option key={c.id} value={c.id}>{c.name}</option>
              ))}
            </select>
          </div>
          <div>
            <label htmlFor="vat-method" className="block text-xs font-semibold text-neutral-500 uppercase tracking-wider mb-1.5">
              VAT201 filing method
            </label>
            <select
              id="vat-method"
              value={vatMethod}
              onChange={(e) => setVatMethod(e.target.value as VatMethod)}
              className="w-full border border-neutral-200 rounded-lg text-sm px-3 py-2 bg-white"
            >
              {VAT_METHODS.map((m) => (
                <option key={m.id} value={m.id}>{m.name}</option>
              ))}
            </select>
          </div>
          <p className="sm:col-span-2 text-2xs text-neutral-500">
            VAT dates shown for {VAT_CATEGORIES.find((c) => c.id === vatCategory)?.name},{" "}
            {VAT_METHODS.find((m) => m.id === vatMethod)?.name} filing:{" "}
            {VAT_METHODS.find((m) => m.id === vatMethod)?.dueRule.toLowerCase()}. Not VAT-registered? Ignore the VAT rows.
          </p>
        </div>

        {/* Next 3 upcoming (needs the visitor's date, so only after hydration) */}
        {upcoming.length > 0 && today && (
          <div>
            <p className="text-xs font-semibold text-neutral-500 uppercase tracking-wider mb-2">Coming up next</p>
            <div className="grid sm:grid-cols-3 gap-3">
              {upcoming.map((d) => {
                const days = daysUntil(d.date, today);
                const style = CATEGORY_STYLES[d.category];
                return (
                  <div key={d.id} className="rounded-xl bg-brand-dark text-white p-4">
                    <span className={`inline-block text-2xs font-semibold px-2 py-0.5 rounded-full border ${style.badge} bg-white/10 border-white/20 text-white mb-2`}>
                      {d.category}
                    </span>
                    <p className="text-sm font-semibold leading-snug">{d.title}</p>
                    <p className="text-2xs text-brand-100 mt-1">{formatDate(d.date)}</p>
                    <p className="text-2xs font-bold text-accent-light mt-2">
                      {days === 0 ? "Due today" : days === 1 ? "Due tomorrow" : `${days} days away`}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* Full timeline, grouped by month */}
        <div>
          <p className="text-xs font-semibold text-neutral-500 uppercase tracking-wider mb-2">Full calendar</p>
          {!today && (
            <p className="text-2xs text-neutral-500 mb-2">
              Showing the full 2026/27 calendar. With JavaScript on, deadlines that have already passed are hidden.
            </p>
          )}
          {today && hiddenPassed > 0 && (
            <p className="text-2xs text-neutral-500 mb-2">{hiddenPassed} earlier deadline{hiddenPassed === 1 ? "" : "s"} already passed and hidden.</p>
          )}
          <div className="space-y-5 max-h-[520px] overflow-y-auto pr-1" data-testid="calendar-list">
            {[...grouped.entries()].map(([monthKey, items]) => (
              <div key={monthKey}>
                <p className="text-2xs font-bold text-neutral-400 uppercase tracking-widest mb-2 sticky top-0 bg-white py-1">
                  {monthHeading(monthKey)}
                </p>
                <ul className="space-y-2">
                  {items.map((d) => {
                    const style = CATEGORY_STYLES[d.category];
                    return (
                      <li
                        key={d.id}
                        data-deadline-id={d.ruleId}
                        data-date={d.date}
                        className="flex gap-3 items-start border border-neutral-100 rounded-lg p-3"
                      >
                        <span className={`w-2 h-2 rounded-full mt-1.5 flex-shrink-0 ${style.dot}`} />
                        <div className="min-w-0 flex-1">
                          <div className="flex items-center gap-2 flex-wrap">
                            <span className="text-sm font-semibold text-neutral-900">{d.title}</span>
                            <span className={`text-2xs font-medium px-2 py-0.5 rounded-full border ${style.badge}`}>{d.category}</span>
                            {d.indicative && (
                              <span className="text-2xs font-medium px-2 py-0.5 rounded-full border bg-neutral-50 text-neutral-500 border-neutral-200">indicative</span>
                            )}
                          </div>
                          <p className="text-xs text-neutral-700 font-medium mt-1">
                            <time dateTime={d.date}>{formatDate(d.date)}</time>
                          </p>
                          {d.adjusted && (
                            <p className="text-2xs text-neutral-500 mt-0.5">
                              Moved from {formatDate(d.nominal)}, which is {d.adjustmentReason}. SARS applies the business day before.
                            </p>
                          )}
                          <p className="text-xs text-neutral-600 mt-1 leading-relaxed">{d.description}</p>
                          <p className="text-2xs text-neutral-400 mt-1" data-source>
                            Source:{" "}
                            <a href={d.source.url} className="underline" rel="noopener noreferrer">{d.source.title}</a>
                            {d.source.gazette ? `, ${d.source.gazette}` : ""}
                          </p>
                        </div>
                      </li>
                    );
                  })}
                </ul>
              </div>
            ))}
            {grouped.size === 0 && (
              <p className="text-sm text-neutral-500 py-6 text-center">No upcoming deadlines in this category for the current window.</p>
            )}
          </div>
        </div>

        {/* Info note */}
        <div className="flex gap-2.5 p-3.5 rounded-lg bg-amber-50 border border-amber-100">
          <Info size={14} className="text-amber-600 flex-shrink-0 mt-0.5" />
          <p className="text-xs text-amber-800 leading-relaxed">
            This calendar covers the standard recurring deadlines that apply to most SME taxpayers.
            It does not include <strong>CIPC Annual Returns</strong>, which fall due 30 business days
            after your specific company&apos;s registration anniversary, or <strong>Annual Financial
            Statement</strong> deadlines, which depend on your entity&apos;s financial year-end.{" "}
            <Link href="/services/company-secretarial" className="underline font-medium">
              Talk to us
            </Link>{" "}
            about your specific dates.
          </p>
        </div>
      </div>
    </div>
  );
}
